/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.CheckPerformanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckPerformance extends TableImpl<CheckPerformanceRecord> {

	private static final long serialVersionUID = -252015469;

	/**
	 * The reference instance of <code>ss1604c195_rd2.check_performance</code>
	 */
	public static final CheckPerformance CHECK_PERFORMANCE = new CheckPerformance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CheckPerformanceRecord> getRecordType() {
		return CheckPerformanceRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.check_performance.performanceid</code>.
	 */
	public final TableField<CheckPerformanceRecord, Integer> PERFORMANCEID = createField("performanceid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.steid</code>.
	 */
	public final TableField<CheckPerformanceRecord, Integer> STEID = createField("steid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.week_lastday</code>.
	 */
	public final TableField<CheckPerformanceRecord, Date> WEEK_LASTDAY = createField("week_lastday", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.hours</code>.
	 */
	public final TableField<CheckPerformanceRecord, Integer> HOURS = createField("hours", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.description</code>.
	 */
	public final TableField<CheckPerformanceRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.state</code>. 1-wait check
2-checked
	 */
	public final TableField<CheckPerformanceRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "1-wait check\r\n2-checked");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.updatedby</code>.
	 */
	public final TableField<CheckPerformanceRecord, Integer> UPDATEDBY = createField("updatedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.createdat</code>.
	 */
	public final TableField<CheckPerformanceRecord, Timestamp> CREATEDAT = createField("createdat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.updatedat</code>.
	 */
	public final TableField<CheckPerformanceRecord, Timestamp> UPDATEDAT = createField("updatedat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.check_performance.week_firstday</code>.
	 */
	public final TableField<CheckPerformanceRecord, Date> WEEK_FIRSTDAY = createField("week_firstday", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>ss1604c195_rd2.check_performance</code> table reference
	 */
	public CheckPerformance() {
		this("check_performance", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.check_performance</code> table reference
	 */
	public CheckPerformance(String alias) {
		this(alias, CHECK_PERFORMANCE);
	}

	private CheckPerformance(String alias, Table<CheckPerformanceRecord> aliased) {
		this(alias, aliased, null);
	}

	private CheckPerformance(String alias, Table<CheckPerformanceRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CheckPerformanceRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CHECK_PERFORMANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CheckPerformanceRecord> getPrimaryKey() {
		return Keys.CHECK_PERFORMANCE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CheckPerformanceRecord>> getKeys() {
		return Arrays.<UniqueKey<CheckPerformanceRecord>>asList(Keys.CHECK_PERFORMANCE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckPerformance as(String alias) {
		return new CheckPerformance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CheckPerformance rename(String name) {
		return new CheckPerformance(name, null);
	}
}
