/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.InfoDepartmentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfoDepartment extends TableImpl<InfoDepartmentRecord> {

	private static final long serialVersionUID = -697937762;

	/**
	 * The reference instance of <code>ss1604c195_rd2.info_department</code>
	 */
	public static final InfoDepartment INFO_DEPARTMENT = new InfoDepartment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InfoDepartmentRecord> getRecordType() {
		return InfoDepartmentRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.info_department.departmentid</code>.
	 */
	public final TableField<InfoDepartmentRecord, Integer> DEPARTMENTID = createField("departmentid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.info_department.departmentname</code>.
	 */
	public final TableField<InfoDepartmentRecord, String> DEPARTMENTNAME = createField("departmentname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.info_department.parent_departmentid</code>.
	 */
	public final TableField<InfoDepartmentRecord, Integer> PARENT_DEPARTMENTID = createField("parent_departmentid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>ss1604c195_rd2.info_department</code> table reference
	 */
	public InfoDepartment() {
		this("info_department", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.info_department</code> table reference
	 */
	public InfoDepartment(String alias) {
		this(alias, INFO_DEPARTMENT);
	}

	private InfoDepartment(String alias, Table<InfoDepartmentRecord> aliased) {
		this(alias, aliased, null);
	}

	private InfoDepartment(String alias, Table<InfoDepartmentRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InfoDepartmentRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INFO_DEPARTMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InfoDepartmentRecord> getPrimaryKey() {
		return Keys.INFO_DEPARTMENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InfoDepartmentRecord>> getKeys() {
		return Arrays.<UniqueKey<InfoDepartmentRecord>>asList(Keys.INFO_DEPARTMENT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoDepartment as(String alias) {
		return new InfoDepartment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InfoDepartment rename(String name) {
		return new InfoDepartment(name, null);
	}
}
