/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.InfoAccountRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfoAccount extends TableImpl<InfoAccountRecord> {

	private static final long serialVersionUID = 1859071218;

	/**
	 * The reference instance of <code>ss1604c195_rd2.info_account</code>
	 */
	public static final InfoAccount INFO_ACCOUNT = new InfoAccount();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InfoAccountRecord> getRecordType() {
		return InfoAccountRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.info_account.accountid</code>.
	 */
	public final TableField<InfoAccountRecord, Integer> ACCOUNTID = createField("accountid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.info_account.email</code>.
	 */
	public final TableField<InfoAccountRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.info_account.password</code>.
	 */
	public final TableField<InfoAccountRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.info_account.refid</code>.
	 */
	public final TableField<InfoAccountRecord, Integer> REFID = createField("refid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.info_account.role</code>. 0-admin
1-hrm
2-hr
3-mg
4-other

10-candidate ste
11-ste
12-dismissed ste
	 */
	public final TableField<InfoAccountRecord, Integer> ROLE = createField("role", org.jooq.impl.SQLDataType.INTEGER, this, "0-admin\r\n1-hrm\r\n2-hr\r\n3-mg\r\n4-other\r\n\r\n10-candidate ste\r\n11-ste\r\n12-dismissed ste");

	/**
	 * Create a <code>ss1604c195_rd2.info_account</code> table reference
	 */
	public InfoAccount() {
		this("info_account", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.info_account</code> table reference
	 */
	public InfoAccount(String alias) {
		this(alias, INFO_ACCOUNT);
	}

	private InfoAccount(String alias, Table<InfoAccountRecord> aliased) {
		this(alias, aliased, null);
	}

	private InfoAccount(String alias, Table<InfoAccountRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InfoAccountRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INFO_ACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InfoAccountRecord> getPrimaryKey() {
		return Keys.INFO_ACCOUNT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InfoAccountRecord>> getKeys() {
		return Arrays.<UniqueKey<InfoAccountRecord>>asList(Keys.INFO_ACCOUNT_PKEY, Keys.INFO_ACCOUNT_EMAIL_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoAccount as(String alias) {
		return new InfoAccount(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InfoAccount rename(String name) {
		return new InfoAccount(name, null);
	}
}
