/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.NotifyPointerRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotifyPointer extends TableImpl<NotifyPointerRecord> {

	private static final long serialVersionUID = 230761369;

	/**
	 * The reference instance of <code>ss1604c195_rd2.notify_pointer</code>
	 */
	public static final NotifyPointer NOTIFY_POINTER = new NotifyPointer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NotifyPointerRecord> getRecordType() {
		return NotifyPointerRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.notify_pointer.ID</code>.
	 */
	public final TableField<NotifyPointerRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.notify_pointer.role</code>.
	 */
	public final TableField<NotifyPointerRecord, Integer> ROLE = createField("role", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.notify_pointer.ref_id</code>.
	 */
	public final TableField<NotifyPointerRecord, Integer> REF_ID = createField("ref_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.notify_pointer.type</code>. 1- inquiry ste applycation
2- inquiry ste salary
3- inqury hr salary
	 */
	public final TableField<NotifyPointerRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "1- inquiry ste applycation\r\n2- inquiry ste salary\r\n3- inqury hr salary");

	/**
	 * The column <code>ss1604c195_rd2.notify_pointer.inquiry_time</code>.
	 */
	public final TableField<NotifyPointerRecord, Timestamp> INQUIRY_TIME = createField("inquiry_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ss1604c195_rd2.notify_pointer</code> table reference
	 */
	public NotifyPointer() {
		this("notify_pointer", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.notify_pointer</code> table reference
	 */
	public NotifyPointer(String alias) {
		this(alias, NOTIFY_POINTER);
	}

	private NotifyPointer(String alias, Table<NotifyPointerRecord> aliased) {
		this(alias, aliased, null);
	}

	private NotifyPointer(String alias, Table<NotifyPointerRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<NotifyPointerRecord, Integer> getIdentity() {
		return Keys.IDENTITY_NOTIFY_POINTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NotifyPointerRecord> getPrimaryKey() {
		return Keys.NOTIFY_POINTER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NotifyPointerRecord>> getKeys() {
		return Arrays.<UniqueKey<NotifyPointerRecord>>asList(Keys.NOTIFY_POINTER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointer as(String alias) {
		return new NotifyPointer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public NotifyPointer rename(String name) {
		return new NotifyPointer(name, null);
	}
}
