/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.RecruitPoolLogRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPoolLog extends TableImpl<RecruitPoolLogRecord> {

	private static final long serialVersionUID = -735751796;

	/**
	 * The reference instance of <code>ss1604c195_rd2.recruit_pool_log</code>
	 */
	public static final RecruitPoolLog RECRUIT_POOL_LOG = new RecruitPoolLog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecruitPoolLogRecord> getRecordType() {
		return RecruitPoolLogRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.positionid</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Integer> POSITIONID = createField("positionid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.realnumber</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Integer> REALNUMBER = createField("realnumber", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.apply_due</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Date> APPLY_DUE = createField("apply_due", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.apply_start</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Date> APPLY_START = createField("apply_start", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.poster_url</code>.
	 */
	public final TableField<RecruitPoolLogRecord, String> POSTER_URL = createField("poster_url", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.createdby</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.updatedby</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Integer> UPDATEDBY = createField("updatedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.createdat</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Timestamp> CREATEDAT = createField("createdat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.updatedat</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Timestamp> UPDATEDAT = createField("updatedat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.poolid</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Integer> POOLID = createField("poolid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.id</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_pool_log.isvalid</code>.
	 */
	public final TableField<RecruitPoolLogRecord, Boolean> ISVALID = createField("isvalid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>ss1604c195_rd2.recruit_pool_log</code> table reference
	 */
	public RecruitPoolLog() {
		this("recruit_pool_log", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.recruit_pool_log</code> table reference
	 */
	public RecruitPoolLog(String alias) {
		this(alias, RECRUIT_POOL_LOG);
	}

	private RecruitPoolLog(String alias, Table<RecruitPoolLogRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecruitPoolLog(String alias, Table<RecruitPoolLogRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecruitPoolLogRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECRUIT_POOL_LOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecruitPoolLogRecord> getPrimaryKey() {
		return Keys.RECRUIT_POOL_LOG_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecruitPoolLogRecord>> getKeys() {
		return Arrays.<UniqueKey<RecruitPoolLogRecord>>asList(Keys.RECRUIT_POOL_LOG_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLog as(String alias) {
		return new RecruitPoolLog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecruitPoolLog rename(String name) {
		return new RecruitPoolLog(name, null);
	}
}
