/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.RecruitApplymentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitApplyment extends TableImpl<RecruitApplymentRecord> {

	private static final long serialVersionUID = 508699007;

	/**
	 * The reference instance of <code>ss1604c195_rd2.recruit_applyment</code>
	 */
	public static final RecruitApplyment RECRUIT_APPLYMENT = new RecruitApplyment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecruitApplymentRecord> getRecordType() {
		return RecruitApplymentRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.steid</code>.
	 */
	public final TableField<RecruitApplymentRecord, Integer> STEID = createField("steid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.positionid</code>.
	 */
	public final TableField<RecruitApplymentRecord, Integer> POSITIONID = createField("positionid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.state</code>. 0-self cancelled
1- wait hr check
2- wait mg check
3- wait arrange interview
4- interview
5- pass
6- fail

	 */
	public final TableField<RecruitApplymentRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "0-self cancelled\r\n1- wait hr check\r\n2- wait mg check\r\n3- wait arrange interview\r\n4- interview\r\n5- pass\r\n6- fail\r\n");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.updatedby</code>.
	 */
	public final TableField<RecruitApplymentRecord, Integer> UPDATEDBY = createField("updatedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.createdat</code>.
	 */
	public final TableField<RecruitApplymentRecord, Timestamp> CREATEDAT = createField("createdat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.updatedat</code>.
	 */
	public final TableField<RecruitApplymentRecord, Timestamp> UPDATEDAT = createField("updatedat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment.applymentid</code>.
	 */
	public final TableField<RecruitApplymentRecord, Integer> APPLYMENTID = createField("applymentid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>ss1604c195_rd2.recruit_applyment</code> table reference
	 */
	public RecruitApplyment() {
		this("recruit_applyment", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.recruit_applyment</code> table reference
	 */
	public RecruitApplyment(String alias) {
		this(alias, RECRUIT_APPLYMENT);
	}

	private RecruitApplyment(String alias, Table<RecruitApplymentRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecruitApplyment(String alias, Table<RecruitApplymentRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecruitApplymentRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECRUIT_APPLYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecruitApplymentRecord> getPrimaryKey() {
		return Keys.RECRUIT_APPLYMENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecruitApplymentRecord>> getKeys() {
		return Arrays.<UniqueKey<RecruitApplymentRecord>>asList(Keys.RECRUIT_APPLYMENT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplyment as(String alias) {
		return new RecruitApplyment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecruitApplyment rename(String name) {
		return new RecruitApplyment(name, null);
	}
}
