/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.RecruitPositionLogRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPositionLog extends TableImpl<RecruitPositionLogRecord> {

	private static final long serialVersionUID = -1490429990;

	/**
	 * The reference instance of <code>ss1604c195_rd2.recruit_position_log</code>
	 */
	public static final RecruitPositionLog RECRUIT_POSITION_LOG = new RecruitPositionLog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecruitPositionLogRecord> getRecordType() {
		return RecruitPositionLogRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.positionname</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> POSITIONNAME = createField("positionname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.number</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Integer> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.location_req</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> LOCATION_REQ = createField("location_req", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.date_req</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Date> DATE_REQ = createField("date_req", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.duration_req</code>. months
	 */
	public final TableField<RecruitPositionLogRecord, Integer> DURATION_REQ = createField("duration_req", org.jooq.impl.SQLDataType.INTEGER, this, "months");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.skill_req1</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> SKILL_REQ1 = createField("skill_req1", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.skill_req2</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> SKILL_REQ2 = createField("skill_req2", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.skill_req3</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> SKILL_REQ3 = createField("skill_req3", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.skill_req4</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> SKILL_REQ4 = createField("skill_req4", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.skill_req5</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> SKILL_REQ5 = createField("skill_req5", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.createdby</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.updatedby</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Integer> UPDATEDBY = createField("updatedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.createdat</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Timestamp> CREATEDAT = createField("createdat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.updatedat</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Timestamp> UPDATEDAT = createField("updatedat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.departmentid</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Integer> DEPARTMENTID = createField("departmentid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.positionid</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Integer> POSITIONID = createField("positionid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.id</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.description</code>.
	 */
	public final TableField<RecruitPositionLogRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_position_log.isvalid</code>.
	 */
	public final TableField<RecruitPositionLogRecord, Boolean> ISVALID = createField("isvalid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>ss1604c195_rd2.recruit_position_log</code> table reference
	 */
	public RecruitPositionLog() {
		this("recruit_position_log", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.recruit_position_log</code> table reference
	 */
	public RecruitPositionLog(String alias) {
		this(alias, RECRUIT_POSITION_LOG);
	}

	private RecruitPositionLog(String alias, Table<RecruitPositionLogRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecruitPositionLog(String alias, Table<RecruitPositionLogRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecruitPositionLogRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECRUIT_POSITION_LOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecruitPositionLogRecord> getPrimaryKey() {
		return Keys.RECRUIT_POSITION_LOG_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecruitPositionLogRecord>> getKeys() {
		return Arrays.<UniqueKey<RecruitPositionLogRecord>>asList(Keys.RECRUIT_POSITION_LOG_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLog as(String alias) {
		return new RecruitPositionLog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecruitPositionLog rename(String name) {
		return new RecruitPositionLog(name, null);
	}
}
