/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.RecruitApplymentLogRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitApplymentLog extends TableImpl<RecruitApplymentLogRecord> {

	private static final long serialVersionUID = -786353174;

	/**
	 * The reference instance of <code>ss1604c195_rd2.recruit_applyment_log</code>
	 */
	public static final RecruitApplymentLog RECRUIT_APPLYMENT_LOG = new RecruitApplymentLog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecruitApplymentLogRecord> getRecordType() {
		return RecruitApplymentLogRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.steid</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Integer> STEID = createField("steid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.positionid</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Integer> POSITIONID = createField("positionid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.state</code>. 0-self cancelled
1- wait hr check
2- wait mg check
3- wait arrange interview
4- interview
5- pass
6- fail

	 */
	public final TableField<RecruitApplymentLogRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "0-self cancelled\r\n1- wait hr check\r\n2- wait mg check\r\n3- wait arrange interview\r\n4- interview\r\n5- pass\r\n6- fail\r\n");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.updatedby</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Integer> UPDATEDBY = createField("updatedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.createdat</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Timestamp> CREATEDAT = createField("createdat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.updatedat</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Timestamp> UPDATEDAT = createField("updatedat", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.applymentid</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Integer> APPLYMENTID = createField("applymentid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.recruit_applyment_log.id</code>.
	 */
	public final TableField<RecruitApplymentLogRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>ss1604c195_rd2.recruit_applyment_log</code> table reference
	 */
	public RecruitApplymentLog() {
		this("recruit_applyment_log", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.recruit_applyment_log</code> table reference
	 */
	public RecruitApplymentLog(String alias) {
		this(alias, RECRUIT_APPLYMENT_LOG);
	}

	private RecruitApplymentLog(String alias, Table<RecruitApplymentLogRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecruitApplymentLog(String alias, Table<RecruitApplymentLogRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecruitApplymentLogRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECRUIT_APPLYMENT_LOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecruitApplymentLogRecord> getPrimaryKey() {
		return Keys.RECRUIT_APPLYMENT_LOG_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecruitApplymentLogRecord>> getKeys() {
		return Arrays.<UniqueKey<RecruitApplymentLogRecord>>asList(Keys.RECRUIT_APPLYMENT_LOG_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLog as(String alias) {
		return new RecruitApplymentLog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecruitApplymentLog rename(String name) {
		return new RecruitApplymentLog(name, null);
	}
}
