/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import com.lucywu.xstem.jooq.domain.Keys;
import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.SnsMessageRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SnsMessage extends TableImpl<SnsMessageRecord> {

	private static final long serialVersionUID = -1104450625;

	/**
	 * The reference instance of <code>ss1604c195_rd2.sns_message</code>
	 */
	public static final SnsMessage SNS_MESSAGE = new SnsMessage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SnsMessageRecord> getRecordType() {
		return SnsMessageRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.sns_message.messageid</code>.
	 */
	public final TableField<SnsMessageRecord, Integer> MESSAGEID = createField("messageid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.sendfrom</code>.
	 */
	public final TableField<SnsMessageRecord, Integer> SENDFROM = createField("sendfrom", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.rolefrom</code>.
	 */
	public final TableField<SnsMessageRecord, Integer> ROLEFROM = createField("rolefrom", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.sendto</code>.
	 */
	public final TableField<SnsMessageRecord, Integer> SENDTO = createField("sendto", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.roleto</code>.
	 */
	public final TableField<SnsMessageRecord, Integer> ROLETO = createField("roleto", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.message</code>.
	 */
	public final TableField<SnsMessageRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.time</code>.
	 */
	public final TableField<SnsMessageRecord, Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ss1604c195_rd2.sns_message.status</code>. 0-sending
1-sent
2-withdraw
	 */
	public final TableField<SnsMessageRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "0-sending\r\n1-sent\r\n2-withdraw");

	/**
	 * Create a <code>ss1604c195_rd2.sns_message</code> table reference
	 */
	public SnsMessage() {
		this("sns_message", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.sns_message</code> table reference
	 */
	public SnsMessage(String alias) {
		this(alias, SNS_MESSAGE);
	}

	private SnsMessage(String alias, Table<SnsMessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private SnsMessage(String alias, Table<SnsMessageRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SnsMessageRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SNS_MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SnsMessageRecord> getPrimaryKey() {
		return Keys.SNS_MESSAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SnsMessageRecord>> getKeys() {
		return Arrays.<UniqueKey<SnsMessageRecord>>asList(Keys.SNS_MESSAGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SnsMessage as(String alias) {
		return new SnsMessage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SnsMessage rename(String name) {
		return new SnsMessage(name, null);
	}
}
