/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables;


import com.lucywu.xstem.jooq.domain.Ss1604c195Rd2;
import com.lucywu.xstem.jooq.domain.tables.records.ViCareerEachMonthRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViCareerEachMonth extends TableImpl<ViCareerEachMonthRecord> {

	private static final long serialVersionUID = -1230577151;

	/**
	 * The reference instance of <code>ss1604c195_rd2.vi_career_each_month</code>
	 */
	public static final ViCareerEachMonth VI_CAREER_EACH_MONTH = new ViCareerEachMonth();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ViCareerEachMonthRecord> getRecordType() {
		return ViCareerEachMonthRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.steid</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Integer> STEID = createField("steid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.name</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.positionid</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Integer> POSITIONID = createField("positionid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.departmentid</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Integer> DEPARTMENTID = createField("departmentid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.positionname</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, String> POSITIONNAME = createField("positionname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.departmentname</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, String> DEPARTMENTNAME = createField("departmentname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.attendancenums</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Long> ATTENDANCENUMS = createField("attendancenums", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.attendancehours</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Long> ATTENDANCEHOURS = createField("attendancehours", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.performancenums</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Long> PERFORMANCENUMS = createField("performancenums", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.performancehours</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, Long> PERFORMANCEHOURS = createField("performancehours", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ss1604c195_rd2.vi_career_each_month.month</code>.
	 */
	public final TableField<ViCareerEachMonthRecord, String> MONTH = createField("month", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>ss1604c195_rd2.vi_career_each_month</code> table reference
	 */
	public ViCareerEachMonth() {
		this("vi_career_each_month", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd2.vi_career_each_month</code> table reference
	 */
	public ViCareerEachMonth(String alias) {
		this(alias, VI_CAREER_EACH_MONTH);
	}

	private ViCareerEachMonth(String alias, Table<ViCareerEachMonthRecord> aliased) {
		this(alias, aliased, null);
	}

	private ViCareerEachMonth(String alias, Table<ViCareerEachMonthRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd2.SS1604C195_RD2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ViCareerEachMonth as(String alias) {
		return new ViCareerEachMonth(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ViCareerEachMonth rename(String name) {
		return new ViCareerEachMonth(name, null);
	}
}
