/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain;


import javax.annotation.Generated;

import com.lucywu.xstem.jooq.domain.tables.CheckAttendance;
import com.lucywu.xstem.jooq.domain.tables.CheckPerformance;
import com.lucywu.xstem.jooq.domain.tables.CheckSkill;
import com.lucywu.xstem.jooq.domain.tables.InfoAccount;
import com.lucywu.xstem.jooq.domain.tables.InfoDepartment;
import com.lucywu.xstem.jooq.domain.tables.InfoFte;
import com.lucywu.xstem.jooq.domain.tables.InfoSte;
import com.lucywu.xstem.jooq.domain.tables.NotifyPointer;
import com.lucywu.xstem.jooq.domain.tables.RecruitAgency;
import com.lucywu.xstem.jooq.domain.tables.RecruitApplyment;
import com.lucywu.xstem.jooq.domain.tables.RecruitApplymentLog;
import com.lucywu.xstem.jooq.domain.tables.RecruitInterview;
import com.lucywu.xstem.jooq.domain.tables.RecruitPool;
import com.lucywu.xstem.jooq.domain.tables.RecruitPoolLog;
import com.lucywu.xstem.jooq.domain.tables.RecruitPosition;
import com.lucywu.xstem.jooq.domain.tables.RecruitPositionLog;
import com.lucywu.xstem.jooq.domain.tables.RecruitPublished;
import com.lucywu.xstem.jooq.domain.tables.SnsMessage;
import com.lucywu.xstem.jooq.domain.tables.SnsTimeline;
import com.lucywu.xstem.jooq.domain.tables.StaffingChange;
import com.lucywu.xstem.jooq.domain.tables.StaffingChangeLog;
import com.lucywu.xstem.jooq.domain.tables.TestComments;
import com.lucywu.xstem.jooq.domain.tables.TestPosts;
import com.lucywu.xstem.jooq.domain.tables.ViCareerEachMonth;
import com.lucywu.xstem.jooq.domain.tables.ViCareerLastMonth;
import com.lucywu.xstem.jooq.domain.tables.ViRecruitApplymentHistory;
import com.lucywu.xstem.jooq.domain.tables.ViRecruitInterviewContext;
import com.lucywu.xstem.jooq.domain.tables.ViRecruitInterviewReminder;


/**
 * Convenience access to all tables in ss1604c195_rd2
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ss1604c195_rd2.check_attendance
	 */
	public static final CheckAttendance CHECK_ATTENDANCE = com.lucywu.xstem.jooq.domain.tables.CheckAttendance.CHECK_ATTENDANCE;

	/**
	 * The table ss1604c195_rd2.check_performance
	 */
	public static final CheckPerformance CHECK_PERFORMANCE = com.lucywu.xstem.jooq.domain.tables.CheckPerformance.CHECK_PERFORMANCE;

	/**
	 * The table ss1604c195_rd2.check_skill
	 */
	public static final CheckSkill CHECK_SKILL = com.lucywu.xstem.jooq.domain.tables.CheckSkill.CHECK_SKILL;

	/**
	 * The table ss1604c195_rd2.info_account
	 */
	public static final InfoAccount INFO_ACCOUNT = com.lucywu.xstem.jooq.domain.tables.InfoAccount.INFO_ACCOUNT;

	/**
	 * The table ss1604c195_rd2.info_department
	 */
	public static final InfoDepartment INFO_DEPARTMENT = com.lucywu.xstem.jooq.domain.tables.InfoDepartment.INFO_DEPARTMENT;

	/**
	 * The table ss1604c195_rd2.info_fte
	 */
	public static final InfoFte INFO_FTE = com.lucywu.xstem.jooq.domain.tables.InfoFte.INFO_FTE;

	/**
	 * The table ss1604c195_rd2.info_ste
	 */
	public static final InfoSte INFO_STE = com.lucywu.xstem.jooq.domain.tables.InfoSte.INFO_STE;

	/**
	 * The table ss1604c195_rd2.notify_pointer
	 */
	public static final NotifyPointer NOTIFY_POINTER = com.lucywu.xstem.jooq.domain.tables.NotifyPointer.NOTIFY_POINTER;

	/**
	 * The table ss1604c195_rd2.recruit_agency
	 */
	public static final RecruitAgency RECRUIT_AGENCY = com.lucywu.xstem.jooq.domain.tables.RecruitAgency.RECRUIT_AGENCY;

	/**
	 * The table ss1604c195_rd2.recruit_applyment
	 */
	public static final RecruitApplyment RECRUIT_APPLYMENT = com.lucywu.xstem.jooq.domain.tables.RecruitApplyment.RECRUIT_APPLYMENT;

	/**
	 * The table ss1604c195_rd2.recruit_applyment_log
	 */
	public static final RecruitApplymentLog RECRUIT_APPLYMENT_LOG = com.lucywu.xstem.jooq.domain.tables.RecruitApplymentLog.RECRUIT_APPLYMENT_LOG;

	/**
	 * The table ss1604c195_rd2.recruit_interview
	 */
	public static final RecruitInterview RECRUIT_INTERVIEW = com.lucywu.xstem.jooq.domain.tables.RecruitInterview.RECRUIT_INTERVIEW;

	/**
	 * The table ss1604c195_rd2.recruit_pool
	 */
	public static final RecruitPool RECRUIT_POOL = com.lucywu.xstem.jooq.domain.tables.RecruitPool.RECRUIT_POOL;

	/**
	 * The table ss1604c195_rd2.recruit_pool_log
	 */
	public static final RecruitPoolLog RECRUIT_POOL_LOG = com.lucywu.xstem.jooq.domain.tables.RecruitPoolLog.RECRUIT_POOL_LOG;

	/**
	 * The table ss1604c195_rd2.recruit_position
	 */
	public static final RecruitPosition RECRUIT_POSITION = com.lucywu.xstem.jooq.domain.tables.RecruitPosition.RECRUIT_POSITION;

	/**
	 * The table ss1604c195_rd2.recruit_position_log
	 */
	public static final RecruitPositionLog RECRUIT_POSITION_LOG = com.lucywu.xstem.jooq.domain.tables.RecruitPositionLog.RECRUIT_POSITION_LOG;

	/**
	 * The table ss1604c195_rd2.recruit_published
	 */
	public static final RecruitPublished RECRUIT_PUBLISHED = com.lucywu.xstem.jooq.domain.tables.RecruitPublished.RECRUIT_PUBLISHED;

	/**
	 * The table ss1604c195_rd2.sns_message
	 */
	public static final SnsMessage SNS_MESSAGE = com.lucywu.xstem.jooq.domain.tables.SnsMessage.SNS_MESSAGE;

	/**
	 * The table ss1604c195_rd2.sns_timeline
	 */
	public static final SnsTimeline SNS_TIMELINE = com.lucywu.xstem.jooq.domain.tables.SnsTimeline.SNS_TIMELINE;

	/**
	 * The table ss1604c195_rd2.staffing_change
	 */
	public static final StaffingChange STAFFING_CHANGE = com.lucywu.xstem.jooq.domain.tables.StaffingChange.STAFFING_CHANGE;

	/**
	 * The table ss1604c195_rd2.staffing_change_log
	 */
	public static final StaffingChangeLog STAFFING_CHANGE_LOG = com.lucywu.xstem.jooq.domain.tables.StaffingChangeLog.STAFFING_CHANGE_LOG;

	/**
	 * The table ss1604c195_rd2.test_comments
	 */
	public static final TestComments TEST_COMMENTS = com.lucywu.xstem.jooq.domain.tables.TestComments.TEST_COMMENTS;

	/**
	 * The table ss1604c195_rd2.test_posts
	 */
	public static final TestPosts TEST_POSTS = com.lucywu.xstem.jooq.domain.tables.TestPosts.TEST_POSTS;

	/**
	 * The table ss1604c195_rd2.vi_career_each_month
	 */
	public static final ViCareerEachMonth VI_CAREER_EACH_MONTH = com.lucywu.xstem.jooq.domain.tables.ViCareerEachMonth.VI_CAREER_EACH_MONTH;

	/**
	 * The table ss1604c195_rd2.vi_career_last_month
	 */
	public static final ViCareerLastMonth VI_CAREER_LAST_MONTH = com.lucywu.xstem.jooq.domain.tables.ViCareerLastMonth.VI_CAREER_LAST_MONTH;

	/**
	 * The table ss1604c195_rd2.vi_recruit_applyment_history
	 */
	public static final ViRecruitApplymentHistory VI_RECRUIT_APPLYMENT_HISTORY = com.lucywu.xstem.jooq.domain.tables.ViRecruitApplymentHistory.VI_RECRUIT_APPLYMENT_HISTORY;

	/**
	 * The table ss1604c195_rd2.vi_recruit_interview_context
	 */
	public static final ViRecruitInterviewContext VI_RECRUIT_INTERVIEW_CONTEXT = com.lucywu.xstem.jooq.domain.tables.ViRecruitInterviewContext.VI_RECRUIT_INTERVIEW_CONTEXT;

	/**
	 * The table ss1604c195_rd2.vi_recruit_interview_reminder
	 */
	public static final ViRecruitInterviewReminder VI_RECRUIT_INTERVIEW_REMINDER = com.lucywu.xstem.jooq.domain.tables.ViRecruitInterviewReminder.VI_RECRUIT_INTERVIEW_REMINDER;
}
