/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import com.lucywu.xstem.jooq.domain.tables.CheckAttendance;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckAttendanceRecord extends UpdatableRecordImpl<CheckAttendanceRecord> implements Record8<Integer, Integer, Date, Integer, Integer, Integer, Timestamp, Timestamp> {

	private static final long serialVersionUID = -360434232;

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.attendanceid</code>.
	 */
	public void setAttendanceid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.attendanceid</code>.
	 */
	public Integer getAttendanceid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.steid</code>.
	 */
	public void setSteid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.steid</code>.
	 */
	public Integer getSteid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.date</code>.
	 */
	public void setDate(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.date</code>.
	 */
	public Date getDate() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.hours</code>.
	 */
	public void setHours(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.hours</code>.
	 */
	public Integer getHours() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.state</code>. 1. wait check
2. checked
	 */
	public void setState(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.state</code>. 1. wait check
2. checked
	 */
	public Integer getState() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.updatedby</code>.
	 */
	public void setUpdatedby(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.updatedby</code>.
	 */
	public Integer getUpdatedby() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.createdat</code>.
	 */
	public void setCreatedat(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.createdat</code>.
	 */
	public Timestamp getCreatedat() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.check_attendance.updatedat</code>.
	 */
	public void setUpdatedat(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.check_attendance.updatedat</code>.
	 */
	public Timestamp getUpdatedat() {
		return (Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Date, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Date, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CheckAttendance.CHECK_ATTENDANCE.ATTENDANCEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CheckAttendance.CHECK_ATTENDANCE.STEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return CheckAttendance.CHECK_ATTENDANCE.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return CheckAttendance.CHECK_ATTENDANCE.HOURS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return CheckAttendance.CHECK_ATTENDANCE.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return CheckAttendance.CHECK_ATTENDANCE.UPDATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return CheckAttendance.CHECK_ATTENDANCE.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return CheckAttendance.CHECK_ATTENDANCE.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getAttendanceid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getHours();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getUpdatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value1(Integer value) {
		setAttendanceid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value2(Integer value) {
		setSteid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value3(Date value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value4(Integer value) {
		setHours(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value5(Integer value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value6(Integer value) {
		setUpdatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value7(Timestamp value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord value8(Timestamp value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckAttendanceRecord values(Integer value1, Integer value2, Date value3, Integer value4, Integer value5, Integer value6, Timestamp value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CheckAttendanceRecord
	 */
	public CheckAttendanceRecord() {
		super(CheckAttendance.CHECK_ATTENDANCE);
	}

	/**
	 * Create a detached, initialised CheckAttendanceRecord
	 */
	public CheckAttendanceRecord(Integer attendanceid, Integer steid, Date date, Integer hours, Integer state, Integer updatedby, Timestamp createdat, Timestamp updatedat) {
		super(CheckAttendance.CHECK_ATTENDANCE);

		setValue(0, attendanceid);
		setValue(1, steid);
		setValue(2, date);
		setValue(3, hours);
		setValue(4, state);
		setValue(5, updatedby);
		setValue(6, createdat);
		setValue(7, updatedat);
	}
}
