/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import com.lucywu.xstem.jooq.domain.tables.InfoFte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfoFteRecord extends UpdatableRecordImpl<InfoFteRecord> implements Record11<Integer, String, String, Boolean, String, Integer, Date, String, Integer, String, String> {

	private static final long serialVersionUID = 1507412373;

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.fteid</code>.
	 */
	public void setFteid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.fteid</code>.
	 */
	public Integer getFteid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.email</code>.
	 */
	public void setEmail(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.email</code>.
	 */
	public String getEmail() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.gender</code>.
	 */
	public void setGender(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.gender</code>.
	 */
	public Boolean getGender() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.telephone</code>.
	 */
	public void setTelephone(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.telephone</code>.
	 */
	public String getTelephone() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.departmentid</code>.
	 */
	public void setDepartmentid(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.departmentid</code>.
	 */
	public Integer getDepartmentid() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.birthday</code>.
	 */
	public void setBirthday(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.birthday</code>.
	 */
	public Date getBirthday() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.location</code>.
	 */
	public void setLocation(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.location</code>.
	 */
	public String getLocation() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.role</code>. 0-admin
1-hrm
2-hr
3-mg
4-other
	 */
	public void setRole(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.role</code>. 0-admin
1-hrm
2-hr
3-mg
4-other
	 */
	public Integer getRole() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.email_self</code>.
	 */
	public void setEmailSelf(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.email_self</code>.
	 */
	public String getEmailSelf() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.info_fte.phone</code>.
	 */
	public void setPhone(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.info_fte.phone</code>.
	 */
	public String getPhone() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, String, Boolean, String, Integer, Date, String, Integer, String, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, String, Boolean, String, Integer, Date, String, Integer, String, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return InfoFte.INFO_FTE.FTEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return InfoFte.INFO_FTE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return InfoFte.INFO_FTE.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return InfoFte.INFO_FTE.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return InfoFte.INFO_FTE.TELEPHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return InfoFte.INFO_FTE.DEPARTMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return InfoFte.INFO_FTE.BIRTHDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return InfoFte.INFO_FTE.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return InfoFte.INFO_FTE.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return InfoFte.INFO_FTE.EMAIL_SELF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return InfoFte.INFO_FTE.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getFteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTelephone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getDepartmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getBirthday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getEmailSelf();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value1(Integer value) {
		setFteid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value3(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value4(Boolean value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value5(String value) {
		setTelephone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value6(Integer value) {
		setDepartmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value7(Date value) {
		setBirthday(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value8(String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value9(Integer value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value10(String value) {
		setEmailSelf(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord value11(String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InfoFteRecord values(Integer value1, String value2, String value3, Boolean value4, String value5, Integer value6, Date value7, String value8, Integer value9, String value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InfoFteRecord
	 */
	public InfoFteRecord() {
		super(InfoFte.INFO_FTE);
	}

	/**
	 * Create a detached, initialised InfoFteRecord
	 */
	public InfoFteRecord(Integer fteid, String name, String email, Boolean gender, String telephone, Integer departmentid, Date birthday, String location, Integer role, String emailSelf, String phone) {
		super(InfoFte.INFO_FTE);

		setValue(0, fteid);
		setValue(1, name);
		setValue(2, email);
		setValue(3, gender);
		setValue(4, telephone);
		setValue(5, departmentid);
		setValue(6, birthday);
		setValue(7, location);
		setValue(8, role);
		setValue(9, emailSelf);
		setValue(10, phone);
	}
}
