/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import com.lucywu.xstem.jooq.domain.tables.NotifyPointer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotifyPointerRecord extends UpdatableRecordImpl<NotifyPointerRecord> implements Record5<Integer, Integer, Integer, Integer, Timestamp> {

	private static final long serialVersionUID = 1006315367;

	/**
	 * Setter for <code>ss1604c195_rd2.notify_pointer.ID</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.notify_pointer.ID</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.notify_pointer.role</code>.
	 */
	public void setRole(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.notify_pointer.role</code>.
	 */
	public Integer getRole() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.notify_pointer.ref_id</code>.
	 */
	public void setRefId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.notify_pointer.ref_id</code>.
	 */
	public Integer getRefId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.notify_pointer.type</code>. 1- inquiry ste applycation
2- inquiry ste salary
3- inqury hr salary
	 */
	public void setType(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.notify_pointer.type</code>. 1- inquiry ste applycation
2- inquiry ste salary
3- inqury hr salary
	 */
	public Integer getType() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.notify_pointer.inquiry_time</code>.
	 */
	public void setInquiryTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.notify_pointer.inquiry_time</code>.
	 */
	public Timestamp getInquiryTime() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return NotifyPointer.NOTIFY_POINTER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return NotifyPointer.NOTIFY_POINTER.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return NotifyPointer.NOTIFY_POINTER.REF_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return NotifyPointer.NOTIFY_POINTER.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return NotifyPointer.NOTIFY_POINTER.INQUIRY_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getRefId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getInquiryTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointerRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointerRecord value2(Integer value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointerRecord value3(Integer value) {
		setRefId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointerRecord value4(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointerRecord value5(Timestamp value) {
		setInquiryTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotifyPointerRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotifyPointerRecord
	 */
	public NotifyPointerRecord() {
		super(NotifyPointer.NOTIFY_POINTER);
	}

	/**
	 * Create a detached, initialised NotifyPointerRecord
	 */
	public NotifyPointerRecord(Integer id, Integer role, Integer refId, Integer type, Timestamp inquiryTime) {
		super(NotifyPointer.NOTIFY_POINTER);

		setValue(0, id);
		setValue(1, role);
		setValue(2, refId);
		setValue(3, type);
		setValue(4, inquiryTime);
	}
}
