/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import com.lucywu.xstem.jooq.domain.tables.RecruitApplymentLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitApplymentLogRecord extends UpdatableRecordImpl<RecruitApplymentLogRecord> implements Record8<Integer, Integer, Integer, Integer, Timestamp, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 156952411;

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.steid</code>.
	 */
	public void setSteid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.steid</code>.
	 */
	public Integer getSteid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.positionid</code>.
	 */
	public void setPositionid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.positionid</code>.
	 */
	public Integer getPositionid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.state</code>. 0-self cancelled
1- wait hr check
2- wait mg check
3- wait arrange interview
4- interview
5- pass
6- fail

	 */
	public void setState(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.state</code>. 0-self cancelled
1- wait hr check
2- wait mg check
3- wait arrange interview
4- interview
5- pass
6- fail

	 */
	public Integer getState() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.updatedby</code>.
	 */
	public void setUpdatedby(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.updatedby</code>.
	 */
	public Integer getUpdatedby() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.createdat</code>.
	 */
	public void setCreatedat(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.createdat</code>.
	 */
	public Timestamp getCreatedat() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.updatedat</code>.
	 */
	public void setUpdatedat(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.updatedat</code>.
	 */
	public Timestamp getUpdatedat() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.applymentid</code>.
	 */
	public void setApplymentid(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.applymentid</code>.
	 */
	public Integer getApplymentid() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_applyment_log.id</code>.
	 */
	public void setId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_applyment_log.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, Timestamp, Timestamp, Integer, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, Timestamp, Timestamp, Integer, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.STEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.POSITIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.UPDATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.APPLYMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return RecruitApplymentLog.RECRUIT_APPLYMENT_LOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getSteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPositionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getUpdatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getApplymentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value1(Integer value) {
		setSteid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value2(Integer value) {
		setPositionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value3(Integer value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value4(Integer value) {
		setUpdatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value5(Timestamp value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value6(Timestamp value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value7(Integer value) {
		setApplymentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord value8(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitApplymentLogRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, Integer value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecruitApplymentLogRecord
	 */
	public RecruitApplymentLogRecord() {
		super(RecruitApplymentLog.RECRUIT_APPLYMENT_LOG);
	}

	/**
	 * Create a detached, initialised RecruitApplymentLogRecord
	 */
	public RecruitApplymentLogRecord(Integer steid, Integer positionid, Integer state, Integer updatedby, Timestamp createdat, Timestamp updatedat, Integer applymentid, Integer id) {
		super(RecruitApplymentLog.RECRUIT_APPLYMENT_LOG);

		setValue(0, steid);
		setValue(1, positionid);
		setValue(2, state);
		setValue(3, updatedby);
		setValue(4, createdat);
		setValue(5, updatedat);
		setValue(6, applymentid);
		setValue(7, id);
	}
}
