/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import com.lucywu.xstem.jooq.domain.tables.RecruitPool;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPoolRecord extends UpdatableRecordImpl<RecruitPoolRecord> implements Record11<Integer, Integer, Integer, Date, Date, String, Integer, Integer, Timestamp, Timestamp, Boolean> {

	private static final long serialVersionUID = 1444907906;

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.poolid</code>.
	 */
	public void setPoolid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.poolid</code>.
	 */
	public Integer getPoolid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.positionid</code>.
	 */
	public void setPositionid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.positionid</code>.
	 */
	public Integer getPositionid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.realnumber</code>.
	 */
	public void setRealnumber(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.realnumber</code>.
	 */
	public Integer getRealnumber() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.apply_due</code>.
	 */
	public void setApplyDue(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.apply_due</code>.
	 */
	public Date getApplyDue() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.apply_start</code>.
	 */
	public void setApplyStart(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.apply_start</code>.
	 */
	public Date getApplyStart() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.poster_url</code>.
	 */
	public void setPosterUrl(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.poster_url</code>.
	 */
	public String getPosterUrl() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.createdby</code>.
	 */
	public void setCreatedby(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.createdby</code>.
	 */
	public Integer getCreatedby() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.updatedby</code>.
	 */
	public void setUpdatedby(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.updatedby</code>.
	 */
	public Integer getUpdatedby() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.createdat</code>.
	 */
	public void setCreatedat(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.createdat</code>.
	 */
	public Timestamp getCreatedat() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.updatedat</code>.
	 */
	public void setUpdatedat(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.updatedat</code>.
	 */
	public Timestamp getUpdatedat() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool.isvalid</code>.
	 */
	public void setIsvalid(Boolean value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool.isvalid</code>.
	 */
	public Boolean getIsvalid() {
		return (Boolean) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, Date, Date, String, Integer, Integer, Timestamp, Timestamp, Boolean> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, Date, Date, String, Integer, Integer, Timestamp, Timestamp, Boolean> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RecruitPool.RECRUIT_POOL.POOLID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RecruitPool.RECRUIT_POOL.POSITIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return RecruitPool.RECRUIT_POOL.REALNUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return RecruitPool.RECRUIT_POOL.APPLY_DUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return RecruitPool.RECRUIT_POOL.APPLY_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return RecruitPool.RECRUIT_POOL.POSTER_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return RecruitPool.RECRUIT_POOL.CREATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return RecruitPool.RECRUIT_POOL.UPDATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return RecruitPool.RECRUIT_POOL.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return RecruitPool.RECRUIT_POOL.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field11() {
		return RecruitPool.RECRUIT_POOL.ISVALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPoolid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPositionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getRealnumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getApplyDue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getApplyStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getPosterUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getCreatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getUpdatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value11() {
		return getIsvalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value1(Integer value) {
		setPoolid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value2(Integer value) {
		setPositionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value3(Integer value) {
		setRealnumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value4(Date value) {
		setApplyDue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value5(Date value) {
		setApplyStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value6(String value) {
		setPosterUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value7(Integer value) {
		setCreatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value8(Integer value) {
		setUpdatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value9(Timestamp value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value10(Timestamp value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord value11(Boolean value) {
		setIsvalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolRecord values(Integer value1, Integer value2, Integer value3, Date value4, Date value5, String value6, Integer value7, Integer value8, Timestamp value9, Timestamp value10, Boolean value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecruitPoolRecord
	 */
	public RecruitPoolRecord() {
		super(RecruitPool.RECRUIT_POOL);
	}

	/**
	 * Create a detached, initialised RecruitPoolRecord
	 */
	public RecruitPoolRecord(Integer poolid, Integer positionid, Integer realnumber, Date applyDue, Date applyStart, String posterUrl, Integer createdby, Integer updatedby, Timestamp createdat, Timestamp updatedat, Boolean isvalid) {
		super(RecruitPool.RECRUIT_POOL);

		setValue(0, poolid);
		setValue(1, positionid);
		setValue(2, realnumber);
		setValue(3, applyDue);
		setValue(4, applyStart);
		setValue(5, posterUrl);
		setValue(6, createdby);
		setValue(7, updatedby);
		setValue(8, createdat);
		setValue(9, updatedat);
		setValue(10, isvalid);
	}
}
