/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import com.lucywu.xstem.jooq.domain.tables.RecruitPosition;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPositionRecord extends UpdatableRecordImpl<RecruitPositionRecord> implements Record18<String, Integer, String, Date, Integer, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, String, Boolean> {

	private static final long serialVersionUID = 1269692956;

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.positionname</code>.
	 */
	public void setPositionname(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.positionname</code>.
	 */
	public String getPositionname() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.number</code>.
	 */
	public void setNumber(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.number</code>.
	 */
	public Integer getNumber() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.location_req</code>.
	 */
	public void setLocationReq(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.location_req</code>.
	 */
	public String getLocationReq() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.date_req</code>.
	 */
	public void setDateReq(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.date_req</code>.
	 */
	public Date getDateReq() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.duration_req</code>. months
	 */
	public void setDurationReq(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.duration_req</code>. months
	 */
	public Integer getDurationReq() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.skill_req1</code>.
	 */
	public void setSkillReq1(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.skill_req1</code>.
	 */
	public String getSkillReq1() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.skill_req2</code>.
	 */
	public void setSkillReq2(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.skill_req2</code>.
	 */
	public String getSkillReq2() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.skill_req3</code>.
	 */
	public void setSkillReq3(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.skill_req3</code>.
	 */
	public String getSkillReq3() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.skill_req4</code>.
	 */
	public void setSkillReq4(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.skill_req4</code>.
	 */
	public String getSkillReq4() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.skill_req5</code>.
	 */
	public void setSkillReq5(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.skill_req5</code>.
	 */
	public String getSkillReq5() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.createdby</code>.
	 */
	public void setCreatedby(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.createdby</code>.
	 */
	public Integer getCreatedby() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.updatedby</code>.
	 */
	public void setUpdatedby(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.updatedby</code>.
	 */
	public Integer getUpdatedby() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.createdat</code>.
	 */
	public void setCreatedat(Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.createdat</code>.
	 */
	public Timestamp getCreatedat() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.updatedat</code>.
	 */
	public void setUpdatedat(Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.updatedat</code>.
	 */
	public Timestamp getUpdatedat() {
		return (Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.departmentid</code>.
	 */
	public void setDepartmentid(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.departmentid</code>.
	 */
	public Integer getDepartmentid() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.positionid</code>.
	 */
	public void setPositionid(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.positionid</code>.
	 */
	public Integer getPositionid() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.description</code>.
	 */
	public void setDescription(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position.isvalid</code>.
	 */
	public void setIsvalid(Boolean value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position.isvalid</code>.
	 */
	public Boolean getIsvalid() {
		return (Boolean) getValue(17);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record18 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row18<String, Integer, String, Date, Integer, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, String, Boolean> fieldsRow() {
		return (Row18) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row18<String, Integer, String, Date, Integer, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, String, Boolean> valuesRow() {
		return (Row18) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return RecruitPosition.RECRUIT_POSITION.POSITIONNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RecruitPosition.RECRUIT_POSITION.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RecruitPosition.RECRUIT_POSITION.LOCATION_REQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return RecruitPosition.RECRUIT_POSITION.DATE_REQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return RecruitPosition.RECRUIT_POSITION.DURATION_REQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return RecruitPosition.RECRUIT_POSITION.SKILL_REQ1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return RecruitPosition.RECRUIT_POSITION.SKILL_REQ2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return RecruitPosition.RECRUIT_POSITION.SKILL_REQ3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return RecruitPosition.RECRUIT_POSITION.SKILL_REQ4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return RecruitPosition.RECRUIT_POSITION.SKILL_REQ5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return RecruitPosition.RECRUIT_POSITION.CREATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return RecruitPosition.RECRUIT_POSITION.UPDATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field13() {
		return RecruitPosition.RECRUIT_POSITION.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field14() {
		return RecruitPosition.RECRUIT_POSITION.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return RecruitPosition.RECRUIT_POSITION.DEPARTMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return RecruitPosition.RECRUIT_POSITION.POSITIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field17() {
		return RecruitPosition.RECRUIT_POSITION.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field18() {
		return RecruitPosition.RECRUIT_POSITION.ISVALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPositionname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLocationReq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getDateReq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getDurationReq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getSkillReq1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSkillReq2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getSkillReq3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSkillReq4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSkillReq5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getCreatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getUpdatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value13() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value14() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getDepartmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getPositionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value17() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value18() {
		return getIsvalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value1(String value) {
		setPositionname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value2(Integer value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value3(String value) {
		setLocationReq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value4(Date value) {
		setDateReq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value5(Integer value) {
		setDurationReq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value6(String value) {
		setSkillReq1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value7(String value) {
		setSkillReq2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value8(String value) {
		setSkillReq3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value9(String value) {
		setSkillReq4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value10(String value) {
		setSkillReq5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value11(Integer value) {
		setCreatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value12(Integer value) {
		setUpdatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value13(Timestamp value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value14(Timestamp value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value15(Integer value) {
		setDepartmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value16(Integer value) {
		setPositionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value17(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord value18(Boolean value) {
		setIsvalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionRecord values(String value1, Integer value2, String value3, Date value4, Integer value5, String value6, String value7, String value8, String value9, String value10, Integer value11, Integer value12, Timestamp value13, Timestamp value14, Integer value15, Integer value16, String value17, Boolean value18) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecruitPositionRecord
	 */
	public RecruitPositionRecord() {
		super(RecruitPosition.RECRUIT_POSITION);
	}

	/**
	 * Create a detached, initialised RecruitPositionRecord
	 */
	public RecruitPositionRecord(String positionname, Integer number, String locationReq, Date dateReq, Integer durationReq, String skillReq1, String skillReq2, String skillReq3, String skillReq4, String skillReq5, Integer createdby, Integer updatedby, Timestamp createdat, Timestamp updatedat, Integer departmentid, Integer positionid, String description, Boolean isvalid) {
		super(RecruitPosition.RECRUIT_POSITION);

		setValue(0, positionname);
		setValue(1, number);
		setValue(2, locationReq);
		setValue(3, dateReq);
		setValue(4, durationReq);
		setValue(5, skillReq1);
		setValue(6, skillReq2);
		setValue(7, skillReq3);
		setValue(8, skillReq4);
		setValue(9, skillReq5);
		setValue(10, createdby);
		setValue(11, updatedby);
		setValue(12, createdat);
		setValue(13, updatedat);
		setValue(14, departmentid);
		setValue(15, positionid);
		setValue(16, description);
		setValue(17, isvalid);
	}
}
