/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import com.lucywu.xstem.jooq.domain.tables.RecruitPoolLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPoolLogRecord extends UpdatableRecordImpl<RecruitPoolLogRecord> implements Record12<Integer, Integer, Date, Date, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Boolean> {

	private static final long serialVersionUID = 684890193;

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.positionid</code>.
	 */
	public void setPositionid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.positionid</code>.
	 */
	public Integer getPositionid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.realnumber</code>.
	 */
	public void setRealnumber(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.realnumber</code>.
	 */
	public Integer getRealnumber() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.apply_due</code>.
	 */
	public void setApplyDue(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.apply_due</code>.
	 */
	public Date getApplyDue() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.apply_start</code>.
	 */
	public void setApplyStart(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.apply_start</code>.
	 */
	public Date getApplyStart() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.poster_url</code>.
	 */
	public void setPosterUrl(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.poster_url</code>.
	 */
	public String getPosterUrl() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.createdby</code>.
	 */
	public void setCreatedby(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.createdby</code>.
	 */
	public Integer getCreatedby() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.updatedby</code>.
	 */
	public void setUpdatedby(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.updatedby</code>.
	 */
	public Integer getUpdatedby() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.createdat</code>.
	 */
	public void setCreatedat(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.createdat</code>.
	 */
	public Timestamp getCreatedat() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.updatedat</code>.
	 */
	public void setUpdatedat(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.updatedat</code>.
	 */
	public Timestamp getUpdatedat() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.poolid</code>.
	 */
	public void setPoolid(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.poolid</code>.
	 */
	public Integer getPoolid() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.id</code>.
	 */
	public void setId(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_pool_log.isvalid</code>.
	 */
	public void setIsvalid(Boolean value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_pool_log.isvalid</code>.
	 */
	public Boolean getIsvalid() {
		return (Boolean) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, Integer, Date, Date, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Boolean> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, Integer, Date, Date, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Boolean> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.POSITIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.REALNUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.APPLY_DUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.APPLY_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.POSTER_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.CREATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.UPDATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.POOLID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field12() {
		return RecruitPoolLog.RECRUIT_POOL_LOG.ISVALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPositionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getRealnumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getApplyDue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getApplyStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPosterUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getCreatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getUpdatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getPoolid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value12() {
		return getIsvalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value1(Integer value) {
		setPositionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value2(Integer value) {
		setRealnumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value3(Date value) {
		setApplyDue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value4(Date value) {
		setApplyStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value5(String value) {
		setPosterUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value6(Integer value) {
		setCreatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value7(Integer value) {
		setUpdatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value8(Timestamp value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value9(Timestamp value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value10(Integer value) {
		setPoolid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value11(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord value12(Boolean value) {
		setIsvalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPoolLogRecord values(Integer value1, Integer value2, Date value3, Date value4, String value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9, Integer value10, Integer value11, Boolean value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecruitPoolLogRecord
	 */
	public RecruitPoolLogRecord() {
		super(RecruitPoolLog.RECRUIT_POOL_LOG);
	}

	/**
	 * Create a detached, initialised RecruitPoolLogRecord
	 */
	public RecruitPoolLogRecord(Integer positionid, Integer realnumber, Date applyDue, Date applyStart, String posterUrl, Integer createdby, Integer updatedby, Timestamp createdat, Timestamp updatedat, Integer poolid, Integer id, Boolean isvalid) {
		super(RecruitPoolLog.RECRUIT_POOL_LOG);

		setValue(0, positionid);
		setValue(1, realnumber);
		setValue(2, applyDue);
		setValue(3, applyStart);
		setValue(4, posterUrl);
		setValue(5, createdby);
		setValue(6, updatedby);
		setValue(7, createdat);
		setValue(8, updatedat);
		setValue(9, poolid);
		setValue(10, id);
		setValue(11, isvalid);
	}
}
