/**
 * This class is generated by jOOQ
 */
package com.lucywu.xstem.jooq.domain.tables.records;


import com.lucywu.xstem.jooq.domain.tables.RecruitPositionLog;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPositionLogRecord extends UpdatableRecordImpl<RecruitPositionLogRecord> implements Record19<String, Integer, String, Date, Integer, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Integer, String, Boolean> {

	private static final long serialVersionUID = -842766608;

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.positionname</code>.
	 */
	public void setPositionname(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.positionname</code>.
	 */
	public String getPositionname() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.number</code>.
	 */
	public void setNumber(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.number</code>.
	 */
	public Integer getNumber() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.location_req</code>.
	 */
	public void setLocationReq(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.location_req</code>.
	 */
	public String getLocationReq() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.date_req</code>.
	 */
	public void setDateReq(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.date_req</code>.
	 */
	public Date getDateReq() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.duration_req</code>. months
	 */
	public void setDurationReq(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.duration_req</code>. months
	 */
	public Integer getDurationReq() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.skill_req1</code>.
	 */
	public void setSkillReq1(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.skill_req1</code>.
	 */
	public String getSkillReq1() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.skill_req2</code>.
	 */
	public void setSkillReq2(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.skill_req2</code>.
	 */
	public String getSkillReq2() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.skill_req3</code>.
	 */
	public void setSkillReq3(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.skill_req3</code>.
	 */
	public String getSkillReq3() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.skill_req4</code>.
	 */
	public void setSkillReq4(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.skill_req4</code>.
	 */
	public String getSkillReq4() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.skill_req5</code>.
	 */
	public void setSkillReq5(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.skill_req5</code>.
	 */
	public String getSkillReq5() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.createdby</code>.
	 */
	public void setCreatedby(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.createdby</code>.
	 */
	public Integer getCreatedby() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.updatedby</code>.
	 */
	public void setUpdatedby(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.updatedby</code>.
	 */
	public Integer getUpdatedby() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.createdat</code>.
	 */
	public void setCreatedat(Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.createdat</code>.
	 */
	public Timestamp getCreatedat() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.updatedat</code>.
	 */
	public void setUpdatedat(Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.updatedat</code>.
	 */
	public Timestamp getUpdatedat() {
		return (Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.departmentid</code>.
	 */
	public void setDepartmentid(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.departmentid</code>.
	 */
	public Integer getDepartmentid() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.positionid</code>.
	 */
	public void setPositionid(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.positionid</code>.
	 */
	public Integer getPositionid() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.id</code>.
	 */
	public void setId(Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(16);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.description</code>.
	 */
	public void setDescription(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>ss1604c195_rd2.recruit_position_log.isvalid</code>.
	 */
	public void setIsvalid(Boolean value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ss1604c195_rd2.recruit_position_log.isvalid</code>.
	 */
	public Boolean getIsvalid() {
		return (Boolean) getValue(18);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record19 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<String, Integer, String, Date, Integer, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Integer, String, Boolean> fieldsRow() {
		return (Row19) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<String, Integer, String, Date, Integer, String, String, String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Integer, String, Boolean> valuesRow() {
		return (Row19) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.POSITIONNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.LOCATION_REQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.DATE_REQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.DURATION_REQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.SKILL_REQ1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.SKILL_REQ2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.SKILL_REQ3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.SKILL_REQ4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.SKILL_REQ5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.CREATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.UPDATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field13() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.CREATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field14() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.UPDATEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.DEPARTMENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.POSITIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field17() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field18() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field19() {
		return RecruitPositionLog.RECRUIT_POSITION_LOG.ISVALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPositionname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLocationReq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getDateReq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getDurationReq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getSkillReq1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSkillReq2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getSkillReq3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSkillReq4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSkillReq5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getCreatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getUpdatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value13() {
		return getCreatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value14() {
		return getUpdatedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getDepartmentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getPositionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value17() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value18() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value19() {
		return getIsvalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value1(String value) {
		setPositionname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value2(Integer value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value3(String value) {
		setLocationReq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value4(Date value) {
		setDateReq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value5(Integer value) {
		setDurationReq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value6(String value) {
		setSkillReq1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value7(String value) {
		setSkillReq2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value8(String value) {
		setSkillReq3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value9(String value) {
		setSkillReq4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value10(String value) {
		setSkillReq5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value11(Integer value) {
		setCreatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value12(Integer value) {
		setUpdatedby(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value13(Timestamp value) {
		setCreatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value14(Timestamp value) {
		setUpdatedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value15(Integer value) {
		setDepartmentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value16(Integer value) {
		setPositionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value17(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value18(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord value19(Boolean value) {
		setIsvalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPositionLogRecord values(String value1, Integer value2, String value3, Date value4, Integer value5, String value6, String value7, String value8, String value9, String value10, Integer value11, Integer value12, Timestamp value13, Timestamp value14, Integer value15, Integer value16, Integer value17, String value18, Boolean value19) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecruitPositionLogRecord
	 */
	public RecruitPositionLogRecord() {
		super(RecruitPositionLog.RECRUIT_POSITION_LOG);
	}

	/**
	 * Create a detached, initialised RecruitPositionLogRecord
	 */
	public RecruitPositionLogRecord(String positionname, Integer number, String locationReq, Date dateReq, Integer durationReq, String skillReq1, String skillReq2, String skillReq3, String skillReq4, String skillReq5, Integer createdby, Integer updatedby, Timestamp createdat, Timestamp updatedat, Integer departmentid, Integer positionid, Integer id, String description, Boolean isvalid) {
		super(RecruitPositionLog.RECRUIT_POSITION_LOG);

		setValue(0, positionname);
		setValue(1, number);
		setValue(2, locationReq);
		setValue(3, dateReq);
		setValue(4, durationReq);
		setValue(5, skillReq1);
		setValue(6, skillReq2);
		setValue(7, skillReq3);
		setValue(8, skillReq4);
		setValue(9, skillReq5);
		setValue(10, createdby);
		setValue(11, updatedby);
		setValue(12, createdat);
		setValue(13, updatedat);
		setValue(14, departmentid);
		setValue(15, positionid);
		setValue(16, id);
		setValue(17, description);
		setValue(18, isvalid);
	}
}
